# Generated by Django 3.1.6 on 2021-02-17 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pride', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
